### ISSUE TITLE
To-do

### ISSUE THREAD

**Issue by blemmmm** [blemmmm/profile-app2#2]
- [x] add /project.config.json to gitignore
- [x] load postgresql username password from project.config.json
- [x] create postgresql_init.sh and postgresql_init.sql
- [x] use "project" as database name, not "db_users"
- [x] add "user.created" column
- [x] remove "roles" table
- [x] remove insert into "roles" on sign up
- [x] add "user.role" column
- [x] validate password length
- [x] use "existing_user_from_username" var on signup
- [x] use 'existing_user_from_email" var on signup
- [x] replace all "setUser" with "set_user"
- [x] user lowercase url slugs (/profile, /signup)
- [x] set user in app.js to null when logging out
- [x] fix status codes response.status >= 400
- [x] show user profile (this is done, needs UI)
- [x] allow updating of user profile
- [x] responsive signup page
- [x] fix button @ homepage
- [x] url for signin page
- [x] url for homepage
- [x] navigation bar
- [x] homepage content
- [x] fix app.js
- [x] add useeffect for the titles and paths
- [x] change your primary key to serial
- [x] show /home page for users, show user stuff
- [x] show /users page for admins, show admin-only stuff
- [x] /profile page: redirect to login when no user is logged in same with edit page (urls not fixed)
- [x] update creation of users

**Comment by blemmmm** [comment]
edit profile
- [x] bio
- [x] favorites
- [x] about me
- [x] username
- [x] name

**Comment by blemmmm** [comment]
- [x] make pages responsive
